export const ABONEMENTS_LOADING = 'ABONEMENTS_LOADING';
export const SAVE_ABONEMENTS = 'SAVE_ABONEMENTS';

export const ABONEMENT_LOADING = 'ABONEMENT_LOADING';
export const SAVE_ABONEMENT = 'SAVE_ABONEMENT';