export const ABONEMENTS_LOADING = 'ABONEMENTS_LOADING';
export const SAVE_ABONEMENTS = 'SAVE_ABONEMENTS';

export const ABONEMENT_LOADING = 'ABONEMENT_LOADING';
export const SAVE_ABONEMENT = 'SAVE_ABONEMENT';

export const ABONEMENTS_BY_STUDENT_LOADING = 'ABONEMENTS_BY_STUDENT_LOADING';
export const SAVE_ABONEMENTS_BY_STUDENT = 'SAVE_ABONEMENTS_BY_STUDENT';

export const ABONEMENTS_BY_DATES_LOADING = 'ABONEMENTS_BY_DATES_LOADING';
export const SAVE_ABONEMENTS_BY_DATES = 'SAVE_ABONEMENTS_BY_DATES';