export const CONFIRMED_LESSONS_LOADING = 'CONFIRMED_LESSONS_LOADING';
export const SAVE_CONFIRMED_LESSONS = 'SAVE_CONFIRMED_LESSONS';

export const CONFIRMED_LESSON_BY_ID_LOADING = 'CONFIRMED_LESSON_BY_ID_LOADING';
export const SAVE_CONFIRMED_LESSON_BY_ID = 'SAVE_CONFIRMED_LESSON_BY_ID';

