export const DELETED_LESSONS_LOADING = 'DELETED_LESSONS_LOADING';
export const SAVE_DELETED_LESSONS = 'SAVE_DELETED_LESSONS';

export const DELETED_LESSON_BY_ID_LOADING = 'DELETED_LESSON_BY_ID_LOADING';
export const SAVE_DELETED_LESSON_BY_ID = 'SAVE_DELETED_LESSON_BY_ID';


