export const LESSONS_LOADING = 'LESSONS_LOADING';
export const SAVE_LESSONS = 'SAVE_LESSONS';

export const LESSON_LOADING = 'LESSON_LOADING';
export const SAVE_LESSON = 'SAVE_LESSON';

export const LESSONS_BY_STUDENT_LOADING = 'LESSONS_BY_STUDENT_LOADING';
export const SAVE_LESSONS_BY_STUDENT = 'LESSON_BY_STUDENT_LOADING';

export const LESSONS_BY_DATE_LOADING = 'LESSONS_BY_DATE_LOADING';
export const SAVE_LESSONS_BY_DATE = 'SAVE_LESSONS_BY_DATE';

export const LESSONS_BY_DAY_LOADING = 'LESSONS_BY_DAY_LOADING';
export const SAVE_LESSONS_BY_DAY = 'SAVE_LESSONS_BY_DAY';




