export const STUDENTS_LOADING = 'STUDENTS_LOADING';
export const SAVE_STUDENTS = 'SAVE_STUDENTS';

export const STUDENT_LOADING = 'STUDENT_LOADING';
export const SAVE_STUDENT = 'SAVE_STUDENT';

export const LOAD_STUDENT_TRANSFERS = 'LOAD_STUDENT_TRANSFERS';
export const STUDENT_TRANSFERS_LOADING = 'STUDENT_TRANSFERS_LOADING';



