export const ALL_TEACHERS_LOADING = 'ALL_TEACHERS_LOADING';
export const SAVE_TEACHERS = 'SAVE_ALL_TEACHERS';

export const TEACHER_LOADING = 'TEACHER_LOADING';
export const SAVE_TEACHER = 'SAVE_TEACHER';
