export const ALL_TEACHERS_LOADING = 'ALL_TEACHERS_LOADING';
export const SAVE_TEACHERS = 'SAVE_ALL_TEACHERS';

export const TEACHER_LOADING = 'TEACHER_LOADING';
export const SAVE_TEACHER = 'SAVE_TEACHER';

export const TEACHERS_BY_DISCIPLINE_LOADING = 'TEACHERS_BY_DISCIPLINE_LOADING';
export const SAVE_TEACHERS_BY_DISCIPLINE = 'SAVE_TEACHERS_BY_DISCIPLINE';

export const TEACHERS_CONFIRMED_LESSONS_LOADING = 'TEACHERS_CONFIRMED_LESSONS_LOADING';
export const SAVE_TEACHERS_CONFIRMED_LESSONS = 'SAVE_TEACHERS_CONFIRMED_LESSONS';
