export const TRANSFERED_LESSONS_LOADING = 'TRANSFERED_LESSONS_LOADING';
export const SAVE_TRANSFERED_LESSONS = 'SAVE_TRANSFERED_LESSONS';

export const LESSON_LOADING = 'LESSON_LOADING';
export const SAVE_LESSON = 'SAVE_LESSON';

export const TRANSFERED_LESSONS_BY_DATE_LOADING = 'TRANSFERED_LESSONS_BY_DATE_LOADING';
export const SAVE_TRANSFERED_LESSONS_BY_DATE = 'SAVE_TRANSFERED_LESSONS_BY_DATE';

export const TRANSFERED_LESSON_BY_ID_LOADING = 'TRANSFERED_LESSON_BY_ID_LOADING';
export const SAVE_TRANSFERED_LESSON_BY_ID = 'SAVE_TRANSFERED_LESSON_BY_ID';




